export type Answers = Record<string,string|string[]>;
export type Question = {id:string;title:string;type:'radio'|'check'|'text'|'number'|'input';options?:string[];hint?:string;optional?:boolean;max?:number;exclusive?:string[];when?:string};
export const FORM_VERSION='2026-09-28-v4-netlify';
export const activeRoles=['Sou proprietário e faço a gestão','Sou proprietário e terceirizo toda a gestão','Sou proprietário e divido a gestão com outra pessoa ou empresa','Administro imóveis de terceiros'];
export const stages=['Seu perfil','Sua rotina','Controle financeiro','Solução e modelo de negócio','Cancelamento e interesse real'];
export const solutionNames=['Básico','Plus','Gestão Completa','Modo Anfitrião (6 ou mais imóveis)'];
export const solutions=[
 {name:'Básico',audience:'Para quem quer organizar a gestão e continuar operando o imóvel.',features:['Calendário único, sincronização de reservas e bloqueio automático entre os canais conectados','Receitas por reserva, taxas dos canais, despesas e saldo por imóvel','Relatório mensal exportável e histórico de lançamentos para conferência'],operation:'Você ou sua equipe cuida dos anúncios, hóspedes, limpeza e manutenção.'},
 {name:'Plus',audience:'Para quem quer automatizar a gestão, mantendo a operação sob sua responsabilidade.',features:['Tudo do Básico','Precificação dinâmica com revisão diária por demanda, antecedência, eventos e sazonalidade, seguindo regras aprovadas por você','Ferramentas de IA para analisar e melhorar títulos, descrições, comodidades e desempenho dos anúncios','Distribuição nos canais conectados e no site próprio, com calendário sincronizado','Automações de atendimento e mensagens aos hóspedes','Tarefas de limpeza e manutenção, checklists com fotos e controle de enxoval e reposições','Resumo anual de receitas e despesas para o contador'],operation:'O sistema organiza e automatiza. A execução física e o atendimento humano ficam com você ou sua equipe.'},
 {name:'Gestão Completa',audience:'Para quem quer delegar a operação à nossa equipe e acompanhar os resultados.',features:['Plataforma Plus e gestão diária pela equipe, com apoio de IA','Implantação do anúncio: fotografia profissional, título, descrição e comodidades trabalhados por imóvel','Publicação, otimização, distribuição multicanal e acompanhamento diário das tarifas','Coordenação e execução com prestadores de limpeza, enxoval e reposições; checklist por imóvel e conferência fotográfica antes de cada chegada','Atendimento humano ao hóspede antes, durante e depois da estadia, com disponibilidade 24 horas e WhatsApp para dúvidas e imprevistos','Vistoria a cada saída e acionamento de pequenos reparos','Prestação de contas mensal conferível: receita por reserva, taxas de canal, despesas e repasse discriminados'],operation:'A equipe assume a operação. Proposta de atendimento presencial inicial em Joinville, sujeita à viabilidade do imóvel.'},
 {name:'Modo Anfitrião',audience:'Para anfitriões e gestores com 6 ou mais imóveis que querem usar somente o sistema.',features:['Tudo do Plus em uma carteira com múltiplos imóveis','Calendário e painel consolidados, com resultados separados por imóvel e proprietário','Acessos e permissões para a equipe e distribuição de tarefas entre responsáveis','Relatórios para prestar contas aos proprietários'],operation:'Você mantém a gestão da carteira e sua equipe ou seus prestadores executam os serviços. Não inclui nossa gestão operacional.'}
];
export const billingOptions=['Mensalidade fixa por imóvel','Percentual sobre as diárias das reservas concluídas e recebidas','Mensalidade única para a carteira de imóveis','Outro'];
export const groups:Question[][]=[
[
 {id:'role',title:'Qual situação descreve você hoje?',type:'radio',options:[...activeRoles,'Comprei um imóvel, mas ainda não comecei a anunciar','Estou avaliando investir, mas ainda não tenho imóvel para temporada','Nenhuma das anteriores']},
 {id:'properties',title:'Quantos imóveis de temporada você acompanha ou administra atualmente?',type:'number',hint:'Conte os imóveis já anunciados, mesmo que estejam sem reservas. Não conte o mesmo imóvel duas vezes por estar em mais de um canal.',when:'active'},
 {id:'location',title:'Onde ficam esses imóveis?',type:'text',hint:'Informe a cidade e o estado. Se tiver imóveis em mais de uma cidade, liste todas. Ex.: Joinville/SC; Curitiba/PR.',when:'active'},
 {id:'tenure',title:'Há quanto tempo você acompanha ou administra imóveis de temporada?',type:'radio',options:['Menos de 3 meses','De 3 a 11 meses','De 1 a menos de 3 anos','3 anos ou mais'],when:'active'},
],
[
 {id:'recent_issues',title:'Nos últimos 30 dias, quais situações mais deram trabalho na administração dos imóveis?',type:'check',hint:'Você pode marcar mais de uma opção.',options:['Atender hóspedes e resolver solicitações','Organizar limpeza e lavanderia','Atualizar calendário e reservas','Definir ou ajustar as diárias','Conferir recebimentos, despesas e repasses','Resolver manutenção e imprevistos','Coordenar prestadores de serviço','Atualizar anúncios e fotos','Acompanhar o trabalho da gestora','Nenhuma situação deu trabalho','Outra situação'],exclusive:['Nenhuma situação deu trabalho']},
 {id:'recent_issue',title:'Conte um caso concreto e como resolveu.',type:'text',optional:true,hint:'Se nada deu trabalho, pode escrever isso. Não informe nomes de hóspedes ou endereços.'},
 {id:'cleaning',title:'Quem costuma executar a limpeza entre uma hospedagem e outra?',type:'check',options:['Eu ou alguém da minha família','Profissional autônomo contratado por mim','Empresa de limpeza contratada por mim','Equipe ou prestador da gestora','Funcionário próprio','Outra pessoa ou solução','Não sei','Ainda não houve troca de hóspedes'],exclusive:['Não sei','Ainda não houve troca de hóspedes']},
 {id:'hours',title:'Nos últimos 30 dias, quanto tempo você pessoalmente dedicou a esses imóveis?',type:'radio',hint:'Some o tempo de todos os imóveis. Inclua atendimento, conferências, deslocamentos e limpeza feita por você. Não inclua as horas dos prestadores.',options:['Nenhum tempo','Menos de 2 horas','De 2 a menos de 5 horas','De 5 a menos de 10 horas','De 10 a menos de 20 horas','De 20 a menos de 40 horas','40 horas ou mais','Não consigo estimar']},
 {id:'time_tasks',title:'Quais atividades mais consumiram seu tempo nesse período?',type:'check',max:3,options:['Responder hóspedes e resolver ocorrências','Atualizar calendário e reservas','Definir ou revisar diárias','Executar limpeza ou lavanderia','Contratar e acompanhar limpeza ou lavanderia','Organizar manutenção e reposições','Conferir pagamentos, despesas e repasses','Acompanhar a empresa que faz a gestão','Atualizar anúncios e fotos','Nenhuma dessas atividades','Outra atividade'],exclusive:['Nenhuma dessas atividades']},
 {id:'tools',title:'O que você usa hoje para administrar ou acompanhar os imóveis?',type:'check',hint:'Marque tudo o que usa, inclusive ferramentas gratuitas.',options:['Recursos gratuitos do Airbnb','Extranet ou app da Booking','Excel ou Google Planilhas','Agenda ou Google Agenda','WhatsApp','Stays','Hospitable','Smoobu','Guesty','Lodgify','PriceLabs ou outra ferramenta de preços','Sistema próprio ou feito sob medida','Sistema ou relatórios da gestora','Outro','Não uso ferramentas','Não sei quais ferramentas a gestora usa'],exclusive:['Não uso ferramentas','Não sei quais ferramentas a gestora usa']},
 {id:'software_spend',title:'Quanto você pagou por sistemas de gestão no último mês?',type:'radio',hint:'Total de todos os imóveis. Não inclua taxas do Airbnb ou Booking, comissão da gestora, limpeza ou contador.',options:['R$0','De R$1 a R$50','De R$51 a R$100','De R$101 a R$200','De R$201 a R$500','De R$501 a R$1.000','Mais de R$1.000','Está incluído na comissão da gestora e não sei separar','Não sei']},
 {id:'diy',title:'Você já tentou criar sua própria forma de organizar a gestão?',type:'radio',options:['Sim, montei uma planilha ou processo manual','Sim, usei ferramentas sem programação ou inteligência artificial','Sim, programei ou contratei um sistema sob medida','Não tentei criar, mas adaptei uma ferramenta pronta','Nunca tentei']},
 {id:'diy_result',title:'O que aconteceu com essa solução?',type:'radio',when:'diy',options:['Uso até hoje e atende bem','Uso, mas ainda faltam coisas importantes','Abandonei porque dava muito trabalho','Abandonei por custo ou problemas técnicos','Ainda estou montando','Outro resultado']}
],
[
 {id:'net_knowledge',title:'Sobre o último mês encerrado, qual frase descreve melhor seu controle do resultado por imóvel?',type:'radio',options:['Sei quanto entrou, quanto saiu e quanto sobrou, com os lançamentos registrados','Tenho uma estimativa do que sobrou, mas não conciliei tudo','Sei quanto recebi, mas não quanto sobrou após as despesas','Dependo da gestora ou de outra pessoa e ainda não conferi','Ainda não tive um mês completo de operação','Prefiro não responder']},
 {id:'finance_method',title:'Como você normalmente confere esse resultado?',type:'radio',options:['Pela minha planilha','Por um sistema de gestão','Pelo relatório da gestora ou do contador','Pelos extratos bancários e repasses dos canais','Faço uma conta aproximada ou de cabeça','Ainda não acompanho','Outra forma']},
 {id:'pain_points',title:'Quais dificuldades aconteceram com você nos últimos 90 dias?',type:'check',max:3,hint:'Escolha até 3. Se nada disso aconteceu, marque a opção correspondente.',options:['Não saber o resultado líquido por imóvel','Gastar tempo copiando informações entre ferramentas','Conflito de datas ou erro de calendário','Falha ou atraso na limpeza','Demora no atendimento ao hóspede','Dificuldade de definir a diária','Dificuldade de conferir despesas ou repasses','Imprevistos de manutenção sem acompanhamento','Organizar informações para o contador','Nenhuma dessas dificuldades','Outra dificuldade'],exclusive:['Nenhuma dessas dificuldades']},
 {id:'wish',title:'Se pudesse melhorar uma única coisa na gestão hoje, o que escolheria?',type:'text',optional:true},
 {id:'tax_current',title:'Como você reúne as informações dos aluguéis para o Imposto de Renda?',type:'radio',options:['Organizo ao longo do ano e envio ao contador','Organizo sozinho quando chega a época de declarar','A gestora ou o sistema já entrega um relatório','O contador busca e organiza as informações para mim','Ainda não tenho uma forma definida','Ainda não precisei fazer isso','Prefiro não responder']}
],
[
 {id:'solution_priorities',title:'Quais entregas dessa proposta teriam mais valor para você?',type:'check',max:3,options:['Precificação dinâmica','Distribuição multicanal e calendário sincronizado','Fotografia e criação ou otimização do anúncio','Organização ou execução de limpeza e enxoval','Atendimento ao hóspede','Manutenção e vistorias','Controle financeiro e prestação de contas','Automações e análises com IA','Nenhuma dessas entregas'],exclusive:['Nenhuma dessas entregas']},
 {id:'solution_choice',title:'Qual solução mais combina com a forma como você gostaria de administrar seus imóveis?',type:'radio',hint:'Considere as entregas e quem executa a operação. Depois, você poderá indicar uma faixa de valor. O Modo Anfitrião é pensado para carteiras com 6 ou mais imóveis.',options:[...solutionNames,'Continuaria com minha solução atual','Nenhuma dessas soluções','Preciso entender melhor antes de escolher']},
 {id:'solution_reason',title:'O que mais pesou nessa escolha? O que faltaria para essa solução fazer sentido?',type:'text',optional:true},
 {id:'billing_preference',title:'Para a solução que você escolheu, qual forma de cobrança você preferiria?',type:'radio',when:'solution',hint:'Compare a mesma solução, com as mesmas entregas. Mensalidade fixa é devida mesmo em meses sem reservas. No percentual, a cobrança varia com a receita e é zero quando não há diárias recebidas. Na mensalidade por carteira, um único valor cobre o conjunto de imóveis contratado. As taxas de Airbnb e Booking continuam separadas.',options:billingOptions},
 {id:'billing_other',title:'Qual outra forma de cobrança você prefere?',type:'text',when:'billing_other',hint:'Descreva como funcionaria. Ex.: pagamento por uso, por reserva ou uma combinação de valores.'},
 {id:'billing_reason',title:'Por que essa forma de cobrança faria mais sentido para você?',type:'text',optional:true,when:'solution',hint:'Pense em previsibilidade, meses sem reservas, alta temporada e custo total.'},
 {id:'billing_reference',title:'Para estimar quanto pagaria nessa outra forma de cobrança, qual unidade você prefere usar?',type:'radio',when:'billing_other',options:['R$/mês por imóvel','Percentual sobre as diárias recebidas','R$/mês pela carteira inteira','Outra unidade de cobrança']},
 {id:'billing_limit',title:'Qual faixa representa o máximo que você consideraria pagar pela solução escolhida?',type:'radio',when:'billing_amount'},
 {id:'billing_limit_other',title:'Qual outro valor você consideraria pagar?',type:'text',when:'billing_limit_other',hint:'Informe o valor estimado e a unidade de cobrança. Se propuser uma combinação, informe cada parte. Ex.: valor por reserva, R$/mês por imóvel ou percentual sobre as diárias.'},
 {id:'decision_condition',title:'O que você precisaria confirmar antes de contratar essa solução?',type:'check',max:2,when:'solution',options:['Preço final e todas as despesas envolvidas','Demonstração ou teste com um imóvel real','Confiabilidade das integrações e dos dados','Economia de tempo na prática','Qualidade da equipe e dos prestadores','Regras de atendimento, contrato e cancelamento','Relatórios e clareza da prestação de contas','Outra condição']}

],
[
 {id:'switch_barriers',title:'O que mais dificultaria começar a usar um sistema novo?',type:'check',max:2,options:['Custo da solução','Tempo para cadastrar e organizar tudo','Medo de erro nas reservas ou no calendário','Dificuldade de aprender a usar','Minha solução atual já resolve','Depender da autorização ou do trabalho da gestora','Dúvidas sobre segurança dos dados','Falta de uma função importante','Nada dificultaria','Outro motivo'],exclusive:['Nada dificultaria']},
 {id:'tax_payment',title:'E se o resumo anual para o contador fosse vendido separadamente, sem assinatura mensal?',type:'radio',hint:'Seria um documento que organiza as receitas e despesas informadas por você. Não inclui cálculo de imposto, declaração de IR, envio à Receita ou serviço de contador. Qual é o maior valor anual que você consideraria pagar?',options:['Não pagaria','Até R$49 por ano','De R$50 a R$99 por ano','De R$100 a R$149 por ano','De R$150 a R$199 por ano','R$200 ou mais por ano','Dependeria do conteúdo e da conferência dos dados','Já recebo esse relatório e não preciso de outro']},
 {id:'final_comment',title:'O que faltou perguntar para entender melhor sua realidade?',type:'text',optional:true},
 {id:'cancel',title:'O que mais faria você cancelar uma plataforma como essa?',type:'check',max:2,options:['Não perceber retorno financeiro','Não economizar tempo','Preço alto','Plataforma complicada','Problemas de integração','Dados incorretos','Precisar continuar usando várias ferramentas','Falta de funcionalidades importantes','Outro']},
 {id:'cancel_other',title:'Qual outro motivo faria você cancelar?',type:'text',when:'cancel_other'},
 {id:'trial_interest',title:'Se essa plataforma estivesse disponível hoje, você teria interesse em testá-la gratuitamente?',type:'radio',options:['Sim','Talvez','Não']},
 {id:'contact_name',title:'Nome',type:'input',when:'trial',hint:'Informe como gostaria de ser chamado(a).'},
 {id:'contact_channel',title:'WhatsApp ou e-mail',type:'input',when:'trial',hint:'Informe um WhatsApp com DDD ou um e-mail. Ao enviar seu nome e contato, você autoriza a equipe da pesquisa a entrar em contato sobre o teste gratuito. Isso não gera compromisso de contratação.'}

]
];
export function active(a:Answers){return activeRoles.includes(String(a.role||''));}
export function visible(q:Question,a:Answers){return (!q.when || q.when==='solution'&&solutionNames.includes(String(a.solution_choice)) || q.when==='billing_amount'&&solutionNames.includes(String(a.solution_choice))&&!!billingUnit(a) || q.when==='billing_other'&&solutionNames.includes(String(a.solution_choice))&&a.billing_preference==='Outro' || q.when==='billing_limit_other'&&solutionNames.includes(String(a.solution_choice))&&!!billingUnit(a)&&a.billing_limit==='Outro valor — informar' || q.when==='active'&&active(a) || q.when==='diy'&&String(a.diy||'').startsWith('Sim,') || q.when==='trial'&&['Sim','Talvez'].includes(String(a.trial_interest)) || q.when==='cancel_other'&&Array.isArray(a.cancel)&&a.cancel.includes('Outro'));}
export function questionsFor(step:number,a:Answers){return groups[step].filter(q=>visible(q,a)).map(q=>resolveQuestion(q,a));}
export function validateQuestions(qs:Question[],a:Answers){const errors:Record<string,string>={};for(const original of qs){const q=resolveQuestion(original,a);const v=a[q.id];if(q.type==='number'){if(!/^\d+$/.test(String(v||''))||Number(v)<1||Number(v)>10000)errors[q.id]='Informe um número inteiro de 1 a 10.000.';continue;}if(q.type==='text'||q.type==='input'){const limit=q.type==='input'?150:1500;if(!q.optional&&(typeof v!=='string'||!v.trim()))errors[q.id]='Preencha este campo.';else if(v!==undefined&&(typeof v!=='string'||v.length>limit))errors[q.id]=`Use um texto de até ${limit} caracteres.`;else if(q.id==='contact_channel'&&typeof v==='string'&&!validContact(v))errors[q.id]='Informe um e-mail válido ou WhatsApp com DDD.';continue;}if(q.type==='radio'){if(typeof v!=='string'||!q.options?.includes(v))errors[q.id]='Escolha uma opção.';continue;}if(!Array.isArray(v)||!v.length||v.some(x=>!q.options?.includes(x))||new Set(v).size!==v.length)errors[q.id]='Selecione ao menos uma opção.';else if(q.max&&v.length>q.max)errors[q.id]=`Escolha até ${q.max} opções.`;else if(v.length>1&&q.exclusive?.some(x=>v.includes(x)))errors[q.id]='Essa opção deve ser marcada sozinha.';}return errors;}
export function cleanAnswers(a:Answers){const qs=active(a)?groups.flat().filter(q=>visible(q,a)):questionsFor(0,a);return Object.fromEntries(qs.map(q=>[q.id,typeof a[q.id]==='string'?(a[q.id] as string).trim():a[q.id]??'']));}

export function validContact(value:string){const v=value.trim();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)||(/^[+\d\s().-]+$/.test(v)&&/^\d{10,15}$/.test(v.replace(/\D/g,'')));}

export const amountUnits=['R$/mês por imóvel','Percentual sobre as diárias recebidas','R$/mês pela carteira inteira','Outra unidade de cobrança'];
export function billingUnit(a:Answers){const i=billingOptions.indexOf(String(a.billing_preference));if(i>=0&&i<3)return amountUnits[i];return a.billing_preference==='Outro'&&amountUnits.includes(String(a.billing_reference))?String(a.billing_reference):'';}
const moneyCuts:Record<string,number[]>={'Básico':[99,149,199,249],'Plus':[149,199,249,299,399],'Gestão Completa':[299,499,799,1199],'Modo Anfitrião (6 ou mais imóveis)':[49,79,119,149]};
const percentageCuts:Record<string,number[]>={'Básico':[1,2,3,5],'Plus':[2,3,5,7],'Gestão Completa':[10,15,20,25],'Modo Anfitrião (6 ou mais imóveis)':[1,2,3,5]};
export function resolveQuestion(q:Question,a:Answers):Question{
 if(q.id!=='billing_limit')return q;
 const unit=billingUnit(a);const solution=String(a.solution_choice);const portfolio=unit===amountUnits[2];const pct=unit===amountUnits[1];const custom=unit===amountUnits[3];
 const n=Number(a.properties);const count=Number.isInteger(n)&&n>0&&n<=10000?n:1;
 const cuts=(pct?percentageCuts[solution]:moneyCuts[solution])||[];
 const format=(v:number)=>pct?`${v}%`:`R$${(v*(portfolio?count:1)).toLocaleString('pt-BR')}`;
 const suffix=pct?' sobre as diárias recebidas':portfolio?`/mês pela carteira de ${count} imóvel(is)`:'/mês por imóvel';
 const bands=custom?[]:cuts.map((v,i)=>i===0?`Até ${format(v)}${suffix}`:`Mais de ${format(cuts[i-1])} até ${format(v)}${suffix}`);
 if(!custom&&cuts.length)bands.push(`Mais de ${format(cuts[cuts.length-1])}${suffix}`);
 return {...q,title:`Quanto você consideraria pagar por ${solution||'essa solução'}?`,hint:custom?'Escolha uma opção. Em “Outro valor”, informe a estimativa e sua unidade.':'Escolha a faixa que contém o seu valor máximo estimado. '+(portfolio?`Considere o valor mensal TOTAL pelos ${count} imóveis informados. `:pct?'Considere o percentual sobre as diárias recebidas, antes das taxas dos canais, sem limpeza ou valores reembolsados. ':'Considere o valor mensal por imóvel. ')+'As faixas são hipóteses de pesquisa, não preços de contratação.',options:['Não pagaria por essa solução',...bands,'Outro valor — informar']};
}
