'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ClipboardList,LockKeyhole} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {encodeSubmission,FORM_NAME} from './netlify-form';
import {active,allVisibleQuestions,Answers,solutions,cleanAnswers,FORM_VERSION,groups,Question,questionsFor,stages,validateQuestions,visible} from './questions';

function QuestionField({q,index,value,error,onChange,onError}:{q:Question;index:number;value:string|string[]|undefined;error?:string;onChange:(id:string,v:string|string[])=>void;onError:(id:string,msg:string)=>void}){
 const id=`q-${q.id}`;
 return <fieldset id={id} className={`question ${error?'has-error':''}`}><legend><span className="q-index">{index+1}</span>{q.title}{q.optional&&<span className="optional">Opcional</span>}</legend>{q.hint&&<p className="hint" id={`${id}-hint`}>{q.hint}</p>}
 {q.type==='input'?<input type="text" aria-label={q.title} aria-invalid={!!error} aria-describedby={q.hint?`${id}-hint`:undefined} className="contact-input" maxLength={150} value={typeof value==='string'?value:''} onChange={e=>onChange(q.id,e.target.value)} autoComplete={q.id==='contact_name'?'given-name':'off'} placeholder={q.id==='contact_name'?'Seu nome':'WhatsApp com DDD ou e-mail'}/>:q.type==='text'?<textarea aria-label={q.title} aria-describedby={q.hint?`${id}-hint`:undefined} value={typeof value==='string'?value:''} maxLength={1500} rows={3} onChange={e=>onChange(q.id,e.target.value)} placeholder="Escreva com suas palavras"/>:q.type==='number'?<input aria-label={q.title} aria-invalid={!!error} type="number" inputMode="numeric" min={1} max={10000} step={1} className="number-input" value={typeof value==='string'?value:''} onChange={e=>onChange(q.id,e.target.value)} placeholder="Ex.: 2"/>:q.type==='radio'?<RadioGroup aria-label={q.title} value={typeof value==='string'?value:''} onValueChange={v=>onChange(q.id,v)} className="options">{q.options?.map((option,i)=><label className={`option ${value===option?'selected':''}`} key={option} htmlFor={`${id}-${i}`}><RadioGroupItem id={`${id}-${i}`} value={option}/><span>{option}</span></label>)}</RadioGroup>:<div className="options">{q.max&&<p className="selection-count">Até {q.max} opções · {Array.isArray(value)?value.length:0} selecionadas</p>}{q.options?.map((option,i)=>{const selected=Array.isArray(value)&&value.includes(option);return <label className={`option ${selected?'selected':''}`} key={option} htmlFor={`${id}-${i}`}><Checkbox id={`${id}-${i}`} checked={selected} onCheckedChange={checked=>{let a=Array.isArray(value)?[...value]:[];if(!checked)a=a.filter(x=>x!==option);else if(q.exclusive?.includes(option))a=[option];else{a=a.filter(x=>!q.exclusive?.includes(x));if(q.max&&a.length>=q.max){onError(q.id,`Escolha até ${q.max} opções.`);return;}a.push(option);}onChange(q.id,a);}}/><span>{option}</span></label>;})}</div>}{error&&<p role="alert" className="field-error">{error}</p>}</fieldset>;
}

export default function Survey({preview=false}:{preview?:boolean}){
 const [answers,setAnswers]=useState<Answers>({});const [step,setStep]=useState(0);const [errors,setErrors]=useState<Record<string,string>>({});
 const [session,setSession]=useState<{id:string}|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);const [ready,setReady]=useState(false);const [consent,setConsent]=useState(false);const [trap,setTrap]=useState('');
 const anchor=useRef<HTMLHeadingElement>(null);const storageKey=`host-survey-${FORM_VERSION}`;const snapshot=useRef({step,answers,done});snapshot.current={step,answers,done};
 useEffect(()=>{if(!preview){try{const x=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(x){setAnswers(x.answers||{});setStep(Number.isInteger(x.step)&&x.step>=0&&x.step<5?x.step:0);setSession(x.session||null);setDone(!!x.done);setConsent(!!x.consent);}}catch{}}setReady(true);},[preview,storageKey]);
 useEffect(()=>{if(ready&&!preview){try{sessionStorage.setItem(storageKey,JSON.stringify({answers,step,session,done,consent}));}catch{}}},[answers,step,session,done,consent,ready,preview,storageKey]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>void}}).modelContext;if(!ctx?.registerTool)return;const ctl=new AbortController();try{ctx.registerTool({name:'read_survey_step',description:'Read the currently visible research questions. Does not answer or submit the survey.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');const s=snapshot.current;return {step:s.step+1,title:stages[s.step],questions:questionsFor(s.step,s.answers).map(q=>({id:q.id,title:q.title,type:q.type,options:q.options||[],required:!q.optional})),submitted:s.done};}},{signal:ctl.signal});}catch{}return()=>ctl.abort();},[]);
 const change=(id:string,value:string|string[])=>{setAnswers(a=>{if(id==='role'&&value!==a.role)return {role:value};const next={...a,[id]:value};if(id==='solution_choice'||id==='billing_preference'||id==='billing_reference'||id==='properties'||id==='future_properties'){delete next.billing_limit;delete next.billing_limit_other;}if(id==='solution_choice'||id==='billing_preference'){delete next.billing_other;delete next.billing_reference;}if(id==='billing_limit'&&value!=='Outro valor — informar')delete next.billing_limit_other;if(id==='trial_interest'&&value==='Não'){delete next.contact_name;delete next.contact_channel;}if(id==='cancel'&&Array.isArray(value)&&!value.includes('Outro'))delete next.cancel_other;return next;});setErrors(e=>({...e,[id]:''}));};
 const move=(s:number)=>{setStep(s);setErrors({});setError('');window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>anchor.current?.focus(),50);};
 function start():{id:string}{if(session)return session;const x={id:preview?'preview':crypto.randomUUID()};setSession(x);return x;}
 async function submit(s:{id:string}){if(!preview){const qs=allVisibleQuestions(answers);const es=validateQuestions(qs,answers);if(Object.keys(es).length){setErrors(es);throw new Error('Confira as respostas obrigatórias antes de enviar.');}if(!consent)throw new Error('Confirme que deseja participar.');const r=await fetch('/netlify-forms.html',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:encodeSubmission(answers,s.id,consent,trap)});if(!r.ok)throw new Error('Não conseguimos salvar. Suas respostas continuam aqui para tentar novamente.');}setDone(true);window.scrollTo({top:0,behavior:'smooth'});}
 async function next(){const es=validateQuestions(questionsFor(step,answers),answers);if(step===0&&!consent)es.consent='Confirme que deseja participar.';setErrors(es);if(Object.keys(es).length){requestAnimationFrame(()=>document.getElementById(`q-${Object.keys(es)[0]}`)?.scrollIntoView({behavior:'smooth',block:'center'}));return;}setBusy(true);setError('');try{const s=await start();if(step===4){await submit(s);return;}move(step+1);}catch(e){setError(e instanceof Error?e.message:'Ocorreu um erro. Tente novamente.');}finally{setBusy(false);}}
 const offset=stages.slice(0,step).flatMap((_,i)=>questionsFor(i,answers)).length;
 return <div className="site-shell"><header className="site-header"><a href="/" className="brand"><span className="brand-icon"><ClipboardList size={21}/></span><span>Pesquisa de gestão <small>Imóveis de temporada · Joinville</small></span></a><span className="header-note">Pesquisa independente</span></header>{preview&&<div className="preview-banner">Prévia para revisão. Nenhuma resposta desta página será salva.</div>}
 <div className="survey-layout"><aside><p className="eyebrow">SUA EXPERIÊNCIA CONTA</p><h1>Ajude a simplificar a gestão de imóveis</h1><p className="intro">Estamos desenvolvendo uma solução digital para facilitar a gestão de imóveis de curta temporada. Esta pesquisa vai nos ajudar a entender sua rotina, seus desafios e o que faria diferença para você.</p><p className="intro">Sua participação é voluntária e não gera compromisso de compra. Você pode encerrar o preenchimento a qualquer momento.</p><nav aria-label="Etapas do formulário"><ol>{stages.map((s,i)=><li key={s} className={done||i<step?'completed':i===step?'current':''}><span>{done||i<step?<Check size={15}/>:i+1}</span>{s}</li>)}</ol></nav><p className="privacy-note"><LockKeyhole size={17}/>No final, quem tiver interesse no teste gratuito poderá informar nome e contato para receber o convite. Não informe CPF, documentos ou dados de hóspedes.</p><a href="/privacidade" className="muted-link">Como usamos as respostas</a></aside>
 <main className="survey-main">{done?<section className="thanks"><span className="success-icon"><Check size={30}/></span><p className="eyebrow">{preview?'PRÉVIA CONCLUÍDA':'RESPOSTA REGISTRADA'}</p><h2>Obrigado por compartilhar sua experiência.</h2><p>Sua resposta vai ajudar a entender experiências, expectativas e quais propostas fazem sentido para diferentes perfis.</p>{!preview&&session&&<p className="receipt">Código da resposta<br/><strong>{session.id}</strong><br/>Guarde este código caso queira solicitar a exclusão pelo mesmo canal em que recebeu a pesquisa.</p>}{preview&&<button className="primary-button" onClick={()=>{setDone(false);move(0);}}>Revisar novamente</button>}</section>:<><div className="stage-heading"><p className="eyebrow">ETAPA {step+1} DE 5</p><h2 ref={anchor} tabIndex={-1}>{stages[step]}</h2><Progress value={(step+1)*20} aria-label={`Etapa ${step+1} de 5`}/></div>{step===0&&<p className="stage-intro">Todos podem participar, mesmo sem ter um imóvel ou experiência com locação. As perguntas se adaptam ao seu momento. Não há respostas certas ou erradas.</p>}
 {step>0&&!active(answers)&&<p className="stage-intro">Como você ainda não acompanha imóveis anunciados, responda pensando nos seus planos ou no que faria sentido para você. Se algo não se aplicar ou ainda não estiver definido, indique isso nas opções.</p>}
 {step===3&&<section className="concept"><p className="concept-label">SOLUÇÃO E MODELO DE NEGÓCIO</p><h3>Uma plataforma 360 com IA para imóveis de curta temporada</h3><p>Imagine reunir reservas, finanças e operação em um sistema web. Você poderia usar a tecnologia com sua própria equipe ou contratar nossa gestão completa. As opções abaixo são propostas em validação, não serviços já disponíveis nem garantia de aumento de receita.</p><div className="plan-grid">{solutions.map(solution=><article className="plan" key={solution.name}><h4>{solution.name}</h4><p>{solution.audience}</p><ul>{solution.features.map(f=><li key={f}>{f}</li>)}</ul><p className="solution-operation"><strong>Quem faz:</strong> {solution.operation}</p></article>)}</div><p className="plan-conditions"><strong>Como interpretar:</strong> fotografia, limpeza, lavanderia, enxoval, consumíveis e reparos têm custos próprios, a serem orçados e discriminados. A Gestão Completa inclui a coordenação desses serviços e o acesso à plataforma; isso não significa que as despesas estejam absorvidas na remuneração da gestora. Básico, Plus e Modo Anfitrião são uso de software, sem contratação da nossa equipe para executar a operação. O resumo para o contador não inclui declaração de IR ou serviço contábil.</p><div className="billing-explanation"><h4>Mensalidade ou percentual sobre reservas?</h4><p>Queremos entender como você prefere pagar pela mesma solução. As faixas de valor apresentadas a seguir são referências para pesquisa, não uma tabela comercial. Se escolher percentual, considere a soma das diárias de reservas concluídas e efetivamente recebidas, antes das taxas dos canais, excluindo limpeza, tributos cobrados à parte e valores cancelados ou reembolsados. Não é percentual sobre o lucro.</p><p>Na Gestão Completa, esse pagamento remunera plataforma e gestão juntas. Nas opções de software, remunera somente o uso da plataforma. Você também pode sugerir outra forma de cobrança no campo “Outro”.</p></div></section>}

 <form name={FORM_NAME} method="POST" action="/netlify-forms.html" onSubmit={e=>{e.preventDefault();void next();}} noValidate><input type="hidden" name="form-name" value={FORM_NAME}/>{questionsFor(step,answers).map((q,i)=><QuestionField key={q.id} q={q} index={offset+i} value={answers[q.id]} error={errors[q.id]} onChange={change} onError={(id,msg)=>setErrors(e=>({...e,[id]:msg}))}/>)}{step===0&&<div id="q-consent" className="consent"><label><Checkbox checked={consent} onCheckedChange={v=>{setConsent(v===true);setErrors(e=>({...e,consent:''}));}}/><span>Quero participar voluntariamente e entendi que as respostas serão usadas nesta pesquisa.</span></label>{errors.consent&&<p className="field-error">{errors.consent}</p>}</div>}<div className="honeypot" aria-hidden="true"><label>Website<input name="website" value={trap} onChange={e=>setTrap(e.target.value)} tabIndex={-1} autoComplete="off"/></label></div>{error&&<p className="submit-error" role="alert">{error}</p>}<footer className="form-actions">{step>0?<button className="back-button" type="button" onClick={()=>move(step-1)} disabled={busy}><ArrowLeft size={18}/>Voltar</button>:<span className="required-note">Campos opcionais estão identificados.</span>}<button className="primary-button" type="submit" disabled={busy}>{busy?'Salvando…':step===4?'Enviar respostas':'Continuar'}{!busy&&<ArrowRight size={18}/>}</button></footer></form></> }</main></div><footer className="site-footer"><a href="/privacidade">Como usamos as respostas</a> <span>Joinville e região · 2026</span></footer></div>;
}
